### ISSUE TITLE
MAINT: drop Python 3.8 soon?

### ISSUE THREAD

**Issue by tylerjereddy** [kokkos/pykokkos#182]
Per [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) I'd like to propose that we drop support for Python `3.8` soon, to keep our maintenance burden sustainable. NumPy and SciPy have both dropped `3.8` support/testing from their `main` branches.

In particular, I had to bend over backwards to support the deprecated Python `3.8` `ast` module behavior at https://github.com/kokkos/pykokkos/pull/181#issuecomment-1452730830, which was quite time consuming to debug.

If you `grep` the code base you can find other examples of shims like that as well.

**Comment by gliga** [comment]
We dropped 3.8, so closing.
