### ISSUE TITLE
BUG: tests/test_views.py fails for CUDA-enabled setup

### ISSUE THREAD

**Issue by tylerjereddy** [kokkos/pykokkos#187]
` python runtests.py -t tests/test_views.py` on a node with V100 GPU/CUDA setup available, on latest `develop` branch:

```
7 failed, 38 passed, 1 xfailed in 22.69s
```

The output is mostly not helpful, but I'll paste one C++ issue that came up in the output:

```
--------------------------------------------------------------------------------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------------------------------------------------------------------------------
/vast/home/treddy/github_projects/spack/opt/spack/linux-rhel8-skylake_avx512/gcc-9.4.0/kokkos-3.7.00-yb3nz2aovt6muketeyv6ri7mitdvzfhu/include/Kokkos_View.hpp(1347): error: static assertion failed with "Incompatible View copy construction"
          detected during instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &, std::enable_if_t<Kokkos::Impl::ViewMapping<Kokkos::View<DataType, Properties...>::traits, Kokkos::View<RT, RP...>::traits, Kokkos::ViewTraits<DataType, Properties...>::specialize>::is_assignable_data_type, void> *) [with DataType=int32_t **, Properties=<Kokkos::LayoutRight, Kokkos::CudaSpace, Kokkos::Experimental::DefaultViewHooks>, RT=int32_t **, RP=<std::conditional_t<true, Kokkos::OpenMP::array_layout, Kokkos::OpenMP::array_layout>, Kokkos::OpenMP>]" 
./bindings.cpp(12): here

/vast/home/treddy/github_projects/spack/opt/spack/linux-rhel8-skylake_avx512/gcc-9.4.0/kokkos-3.7.00-yb3nz2aovt6muketeyv6ri7mitdvzfhu/include/impl/Kokkos_ViewMapping.hpp(3564): error: static assertion failed with "View assignment must have compatible spaces"
          detected during:
            instantiation of "void Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::assign(Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::DstType &, const Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::SrcType &, const Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::TrackType &) [with DstTraits=Kokkos::ViewTraits<int32_t **, Kokkos::LayoutRight, Kokkos::CudaSpace, Kokkos::Experimental::DefaultViewHooks>, SrcTraits=Kokkos::ViewTraits<int32_t **, std::conditional_t<true, Kokkos::OpenMP::array_layout, Kokkos::OpenMP::array_layout>, Kokkos::OpenMP>]" 
/vast/home/treddy/github_projects/spack/opt/spack/linux-rhel8-skylake_avx512/gcc-9.4.0/kokkos-3.7.00-yb3nz2aovt6muketeyv6ri7mitdvzfhu/include/Kokkos_View.hpp(1349): here
            instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &, std::enable_if_t<Kokkos::Impl::ViewMapping<Kokkos::View<DataType, Properties...>::traits, Kokkos::View<RT, RP...>::traits, Kokkos::ViewTraits<DataType, Properties...>::specialize>::is_assignable_data_type, void> *) [with DataType=int32_t **, Properties=<Kokkos::LayoutRight, Kokkos::CudaSpace, Kokkos::Experimental::DefaultViewHooks>, RT=int32_t **, RP=<std::conditional_t<true, Kokkos::OpenMP::array_layout, Kokkos::OpenMP::array_layout>, Kokkos::OpenMP>]" 
./bindings.cpp(12): here

2 errors detected in the compilation of "./bindings.cpp".
nvlink fatal   : Could not open input file './bindings.cpp.o'

C++ compilation in pk_cpp/runtests/test_views_ViewsTestFunctor/OpenMP failed
```

I don't know if this is a genuine issue or something wrong in the dependency chain available on the machine, but a much clearer error message (as usual) would be helpful.

**Comment by tylerjereddy** [comment]
Using `git bisect`, the error changes here:

```diff
commit 8f2bd18a324e4180a7e4a411482fb153a84e4b50 (HEAD)
Author: root <jakob.bludau@tum.de>
Date:   Mon Oct 10 15:09:08 2022 +0000

    support for different precisions in the cast operators

```

and the `git bisect` outcome is (if I `git bisect skip` on the above commit):

```diff
ca4fcff8e008065eb00b1a762b5d00717adab2c8 is the first bad commit
commit ca4fcff8e008065eb00b1a762b5d00717adab2c8
Author: root <jakob.bludau@tum.de>
Date:   Mon Oct 10 03:50:13 2022 +0000

    added constructor without random args as they are not used for the cast

 pykokkos/core/translators/functor.py | 43 ++++++++++++++++++++++++++++++++++++
 1 file changed, 43 insertions(+)
```

**Comment by tylerjereddy** [comment]
If I do a "pure" `git bisect` with no skipping commits, requiring this test to pass with GPU/CUDA available: `python runtests.py -t tests/test_views.py::TestViews::test_dynamic1D`

I get a result that is concealed by a lack of CUDA/NVIDIA GPU testing in CI I think rather than the genuine pinpoint of the problem, since there are actually multiple problems with GPU/Cuda backend that popped up and were fixed over time

```
c474d41fba35630c8e5861c60128fb2d3a73645d is the first bad commit
commit c474d41fba35630c8e5861c60128fb2d3a73645d
Author: Nader Al Awar <naderalawar@gmail.com>
Date:   Mon Oct 24 12:28:08 2022 -0500

    PyKokkos: add support for AMD multi GPUs

 pykokkos/core/cpp_setup.py              |  2 +-
 pykokkos/core/visitors/visitors_util.py |  2 ++
 pykokkos/interface/views.py             |  8 +++++++-
 pykokkos/kokkos_manager/__init__.py     | 17 ++++++++++++++++-
 4 files changed, 26 insertions(+), 3 deletions(-)
```

There was some environment variable that was not used correctly: `FAILED tests/test_views.py::TestViews::test_dynamic1D - KeyError: 'GPU_BACKEND'`

Which I shimmed around in https://github.com/kokkos/pykokkos/pull/131.

Anyway, my point is there seem to be GPU/Cuda testing problems, and the `git` history is somewhat polluted by interwoven problems on GPUs b/c the CI can't test them...

**Comment by JBludau** [comment]
hmm ... if I understand this correctly, it is a problem with the functor having `Kokkos::View<int32_t **, Kokkos::LayoutRight,Kokkos::CudaSpace, ...>` as a data member https://github.com/kokkos/pykokkos/blob/a39282171630803067c8c2f13858e0a9beae2eb9/tests/test_views.py#L36. When we create the functor in the translated `run` function in cpp, we do a `Kokkos::create_mirror_view_and_copy(pk_exec_space_instance,...)`. 
For `Execspace=OpenMP` this should create a view in `Kokkos::HostSpace` as mirror for the view in `KokkosCudaSpace`. 

We pass this as argument to the generated constructor of the functor. But this expects a view in `Kokkos::CudaSpace`. As the two are not directly assignable (living in different memory) Kokkos errors out at compiletime.
Maybe we did forget about this, as this was not relevant when `Kokkos_ENABLE_CUDA_UVM` was still a configure option in Kokkos, as back then everything in the `CudaSpace` would also be assignable to `HostSpace` ... 
Does this make sense?

**Comment by JBludau** [comment]
I agree with @tylerjereddy in that we should try to get a Cuda/Hip runner for the CI

**Comment by JBludau** [comment]
Looks like this originated from a 'not' that I forgot in an if condition ... apparently I did never see this in my tests, as it is only visible with `Kokkos_ENABLE_CUDA_UVM=Off` which I did not have in my testing env
