### ISSUE TITLE
error in installing pykokkos-base

### ISSUE THREAD

**Issue by Rozie100** [kokkos/pykokkos#202]
The following error while installing  pykokkos-base

Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    from skbuild import setup
ModuleNotFoundError: No module named 'skbuild'

**Comment by Zhvhe** [comment]
Have you run Conda part yet? 

conda create --name pyk --file requirements.txt
conda activate pyk

This grabs the scikit-build package and sets up the conda environment that you then build and run in.

**Comment by Zhvhe** [comment]
Conda should not be leaving any files in the directory that is activated (or init-ed) in.
 isMost files should be under the conda or anaconda directory whereever its installed. Conda environment specific set up will be under the envs folder there.

If conda is running (even with just the normal environment) usually there is a (base) prefix to your shell prompt. And when a conda environment is activated that prefix changes to match the environment name, in this case it should be (pyk).

You will need to reactivate the environment every time you re-log in.

To check what is loaded run:  "conda list"
This should give you a list of the packages currently loaded and available in the current conda env (maybe pipe to less or something, it can get pretty long) and at the top it should show the path to where the packages are stored which should also have the name of the current env.
Example: "# packages in environment at /<home_dir?>/anaconda3/envs/pyk:"
if envs is not in the path, then you are in the base environment.

and skbuild should be in there somewhere in the list if the pyk environment init-ed correctly
Example: "scikit-build              0.15.0          py311h6a678d5_0"

If its not, try adding it manually by running (in the pyk environment!) "conda install <package name>"
Example: "conda install cmake>=3.16" (if no version, just the package name works too!) 
All the required packages are in requirements.txt and I think a straight copy/paste after "conda install" should work.

And if you ran all the conda stuff and nothing is happening/envs not set up/something complains... lets take a look at your OS/conda versions.
