### ISSUE TITLE
Use same CXX standard as Kokkos when building python bindings

### ISSUE THREAD

**Issue by pkestene** [kokkos/pykokkos#215]
Currently cxx standard used to build python bindings is hardwired to cxx14 in [compile.sh](https://github.com/kokkos/pykokkos/blob/main/pykokkos/core/compile.sh#L24), but pykokkos-base let the user choose the cxx standard version.

So if a user builds pykokkos-base by explicitely setting a cxx standard different from 14, this is a mismatch.

I suggest to slightly modify compile.sh to retrieve CXX standard version by reading KokkosCore_config.h so that python bindings are compiled with the same cxx standard as kokkos was.

**Comment by NaderAlAwar** [comment]
@pkestene feel free to close the issue if the recent PR fixed it for you

**Comment by pkestene** [comment]
Thanks.
