### ISSUE TITLE
TeamPolicy gpu parallel for hangs on more that 5 serial calls.

### ISSUE THREAD

**Issue by kennykos** [kokkos/pykokkos#279]
I am running into an issue that when I am calling a pk.parallel_for loop sequentially on a gpu more than 5 time in a row, the code hangs.

Here is a minimal example.

```python
import cupy as cp
import pykokkos as pk

@pk.workunit
def work(team_member, view):
    j: int = team_member.league_rank()
    k: int = team_member.team_size()

    def inner(i: int):
        view[j * k + i] = view[j * k + i] + 1

    pk.parallel_for(pk.TeamThreadRange(team_member, k), inner)

def main():
    pk.set_default_space(pk.Cuda)
    a = cp.zeros(100)
    for r in range(6):
        pk.parallel_for("work", pk.TeamPolicy(50, 2), work, view=a)
        print(r)
    print(a)

main()
```

On line 17, when range is set to 5, the code executes, but when range is set to 6, the code fails.

**Comment by NaderAlAwar** [comment]
I'm unable to reproduce this. What CUDA version and GPU are you using? Does this work fine with OpenMP?

**Comment by kennykos** [comment]
It seems to be a CUDA versioning error. When I run the code on CUDA 11.4, everything works fine, but it hangs on CUDA 12.2.

**Comment by NaderAlAwar** [comment]
Did you create two separate conda environments, one for each CUDA version?

**Comment by kennykos** [comment]
No, I've been using the same one for both.

**Comment by NaderAlAwar** [comment]
Typically I use separate environments for different CUDA versions since they use different versions of NVCC. which is needed to compile pykokkos-base. I'm not sure if this is the cause here but it might be worth trying. I would also delete `pk_cpp` when you switch CUDA versions to force compilation with its NVCC.
