### ISSUE TITLE
Is this repo being actively developed?

### ISSUE THREAD

**Issue by ma-sadeghi** [kokkos/pykokkos#41]
Dear Kokkos devs, 

I was wondering if you are actively developing `pykokkos`. We're thinking of a major refactor of two of our Python projects to use `pykokkos` as the backend, wanted to double check with you guys first to see if you plan on long term maintenance of this project.

Thank you,
Amin

**Comment by tylerjereddy** [comment]
Yes, improvements/maintenance still happening -- see the `develop` branch.
