### ISSUE TITLE
MAINT: overflow in 02_simple_reduce.py

### ISSUE THREAD

**Issue by tylerjereddy** [kokkos/pykokkos#6]
For the `02_simple_reduce.py` example, I seem to get overflow if I do i.e., `SquareSum(90000)`. If it isn't too distracting to the example, perhaps switching to `pk.double` for the `self.total` type would be acceptable, and better match the type of the internal accumulator of the sum in any case.

**Comment by NaderAlAwar** [comment]
I merged your PR, but I think I'm gonna keep this issue open. Ideally we would use the `pk.int64` type as the accumulator, but due to the way we return reduction results in the `pk.main` style, we can't do that right now.

**Comment by tylerjereddy** [comment]
Interesting, I *think* NumPy may have been using an integer type when I was doing benchmark comparisons between `pykokkos` and other frameworks today.

I suppose for pure Python one would have to contend with arbitrary precision integers so I don't know if a comparable "upper limit" could be achieved in the compiled code, though I might naively expected `pykokkos` to be able to match NumPy with a fixed-width array type reduction, and perhaps `pk.int64` would eventually provide that.

**Comment by tylerjereddy** [comment]
Before we close this, let me check if `pykokkos` and `numpy` can match for extremely high integer numbers in that style of reduction.

**Comment by tylerjereddy** [comment]
Yeah, looks like `pykokkos` and `numpy` match right up the point of overflow, and even after overflow (see below). Using integers that large doubles the test time for that test, so maybe not worth the tradeoff. I think we can close this then:

```diff
--- a/tests/test_parallelreduce.py
+++ b/tests/test_parallelreduce.py
@@ -47,7 +47,7 @@ class TestParallelReduce(unittest.TestCase):
 @pk.workload
 class SquareSumFloat:
     def __init__(self, n):
-        self.N: int = n
+        self.N: pk.int64 = n
         self.total: pk.double = 0
 
     @pk.main
@@ -62,7 +62,7 @@ class SquareSumFloat:
 @pk.workload
 class SquareSumInt:
     def __init__(self, n):
-        self.N: int = n
+        self.N: pk.int64 = n
         self.total: pk.int64 = 0
 
     @pk.main
@@ -74,7 +74,7 @@ class SquareSumInt:
         acc += i * i
 
 
-@pytest.mark.parametrize("series_max", [10, 5000, 90000])
+@pytest.mark.parametrize("series_max", [10, 5000, 2147483649])
 @pytest.mark.parametrize("dtype", [np.float64, np.int64])
 def test_squaresum_types(series_max, dtype):
     # check for the ability to match NumPy in

```
