### ISSUE TITLE
Power9 OpenMP implementation

### ISSUE THREAD

**Issue by jpmorgan98** [kokkos/pykokkos#8]
Has anybody tried to get the OpenMP implementation working on an IBM Power 9 platform? My current build process is:
1. Compile pykokkos-base with: ` python setup.py install -- -DCMAKE_CXX_COMPILER=g++ -DENABLE_LAYOUTS=ON -DENABLE_MEMORY_TRAITS=OFF -DENABLE_VIEW_RANKS=3 -DENABLE_CUDA=OFF -DENABLE_THREADS=OFF -DENABLE_OPENMP=ON`
3. Establish env variables to requested directories within my conda environment where `pykokkos-base` is installed (only the 2 OMP ones)
4. Run the hello world script and get the following error:

```
(pyk) [morg83@lassen708:try]$ python hello_world.py 
INFO:root:translation 0.0029082302935421467
ERROR: could not get CUDA compute capability
nvcc fatal   : Value '--expt-extended-lambda' is not defined for option 'gpu-architecture'
nvcc fatal   : Value '--expt-extended-lambda' is not defined for option 'gpu-architecture'

C++ compilation in pk_cpp/g/g16/morg83/pykokkos/try/hello_world/hello_world_hello/OpenMP failed
```
I used this same process on multiple x86 platforms with roughly the same modules and did not have this issue. Currently using `gcc/8.3.1` and `cuda/10.2.89` with CPU: `POWER9` and GPU: `Tesla V100`. Is this a limitation of pykokkos right now or something else I am doing?

I am also having a bunch of issues with getting the CUDA implementation working as well on said x86 platforms. After reading the other issues I am thinking maybe I should just hold off until the build docs have been updated? It seems like the process has changed substantially.

Thanks!

**Comment by NaderAlAwar** [comment]
Can you pull develop and try again? Should be fixed. PyKokkos was wrongly trying to use nvcc when CUDA wasn't enabled.

**Comment by jpmorgan98** [comment]
Oh ya that's got it! I was on `main`.

So when I go to setup the CUDA implementation for `pykokkos-base` is this an appropriate build command: `python setup.py install -- -DCMAKE_CXX_COMPILER=g++ -DENABLE_LAYOUTS=ON -DENABLE_MEMORY_TRAITS=OFF -DENABLE_VIEW_RANKS=3 -DENABLE_CUDA=ON -DENABLE_THREADS=OFF -DENABLE_OPENMP=ON -- -j 4` it's same as before just with `CUDA` set to on).

If this is correct it takes a while to fail out but when it does I get the following error. It fails on that 25th operation but keeps chugging to a final stall at 31. Same issue on multiple machines (same environment as before). Any ideas?
```
[25/36] Linking CXX shared library external/kokkos/core/src/libkokkoscore.so.3.4.01
FAILED: external/kokkos/core/src/libkokkoscore.so.3.4.01 
: && /g/g16/morgan83/pykokkos/pykokkos-base/external/kokkos/bin/kokkos_launch_compiler /g/g16/morgan83/pykokkos/pykokkos-base/external/kokkos/bin/nvcc_wrapper /usr/tce/packages/gcc/gcc-8.3.1/bin/c++ /usr/tce/packages/gcc/gcc-8.3.1/bin/c++ -fPIC -O3 -DNDEBUG  -DKOKKOS_DEPENDENCE -fopenmp -arch=sm_70 -shared -Wl,-soname,libkokkoscore.so.3.4 -o external/kokkos/core/src/libkokkoscore.so.3.4.01 @CMakeFiles/kokkoscore.rsp  && :
nvcc fatal   : No input files specified; use option --help for more information
[31/36] Building CXX object src/variants/CMakeFiles/libpykokkos-variants.dir/Unity/unity_concrete_Left_cxx.cxx.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/g/g16/morgan83/.conda/envs/pyk/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 589, in setup
    cmkr.make(make_args, env=env)
  File "/g/g16/morgan83/.conda/envs/pyk/lib/python3.8/site-packages/skbuild/cmaker.py", line 496, in make
    raise SKBuildError(
```

**Comment by NaderAlAwar** [comment]
I think this is a `pykokkos-base` issue. I think ran into this before, and I believe the issue was related to `ninja`. I think using Makefiles fixes this. Could you try deleting the `_skbuild/` directory and re-running the same command, with `-G "Unix Makefiles"` added after `-DENABLE_OPENMP=ON`?

**Comment by jpmorgan98** [comment]
That seems to have worked! Or at least for the hello world. I do get a few runtime errors tho. Is there a place where I can interface directly with Kokkos to set these variables? I am on a multi-gpu node.

```
Kokkos::Cuda::initialize WARNING: Cuda is allocating into UVMSpace by default
                                  without setting CUDA_LAUNCH_BLOCKING=1.
                                  The code must call Cuda().fence() after each kernel
                                  or will likely crash when accessing data on the host.

Kokkos::Cuda::initialize WARNING: Cuda is allocating into UVMSpace by default
                                  without setting CUDA_MANAGED_FORCE_DEVICE_ALLOC=1 or
                                  setting CUDA_VISIBLE_DEVICES.
                                  This could on multi GPU systems lead to severe performance"
                                  penalties.
```
 Besides that I have a few more questions for you if you don't mind:

1. How difficult do you expect the process is to go from running `OpenMP` work units to `Cuda` ones?
2. Do you have any idea what the best way to transfer data from `numpy` arrays into pyk views (right now I am doing this in for-loops which seems less than ideal). 
3. Do you have any specific functions for random number generation or how to make this quicker in your framwork? 

Really excited to do some development using this!

**Comment by NaderAlAwar** [comment]
I'm not sure what you mean by interfacing directly with Kokkos. Setting those environment variables in your terminal would get rid of those warnings.

> How difficult do you expect the process is to go from running OpenMP work units to Cuda ones?

All you need to do is set the default execution space using `pk.set_default_space(pk.Cuda)`, see [here](https://github.com/kokkos/pykokkos/blob/172521965d8f68299d51cfe18217d558d7b915db/examples/kokkos-tutorials/workload/02.py#L78) for an example. All views created afterwards will be in the corresponding memory space and with the appropriate memory layout (see the constructor in the above example).

> Do you have any idea what the best way to transfer data from numpy arrays into pyk views (right now I am doing this in for-loops which seems less than ideal).

You can use `pk.from_numpy(array)` (see [here](https://github.com/kokkos/pykokkos/blob/172521965d8f68299d51cfe18217d558d7b915db/pykokkos/interface/views.py#L369)). I don't have an example of this in the repo right now, but let me know if you run into any issues with this.

> Do you have any specific functions for random number generation or how to make this quicker in your framwork?

We've mostly stuck to using [numpy](https://numpy.org/doc/stable/reference/random/generated/numpy.random.multivariate_normal.html) or [cupy](https://docs.cupy.dev/en/stable/reference/generated/cupy.random.multivariate_normal.html) for RNG and then using `from_numpy()` or `from_cupy()`. Do you need RNG inside kernels? I'm working on adding support for that using the Kokkos RNG algorithm. 

> Really excited to do some development using this!

Sounds good. Let me know if you run into any issues.

**Comment by jpmorgan98** [comment]
An in kernel RNG would be a really great addition! Right now I can't use workloads very efficiently because the computations require an indefinite number of RNs within kernel while loops. Just having single workunit functions seems to be working fine, tho my current implementations don't seem to be very preformant.

**Comment by jpmorgan98** [comment]
Is there some way to get in-kernel random number generation quickly? 

After trying some work arounds, it ends up that random number generation is a bottleneck in my application as the kernel has to exit so more random numbers can be generated every iteration of a function. There is no way to know in advance how many will be required for the whole run.

**Comment by NaderAlAwar** [comment]
@jpmorgan98 I'm going to close this issue. Can open a separate issue for in-kernel RNG?
